SOURCE=detector_test.cpp
MYPROGRAM=detector_test
CC=g++



all: $(MYPROGRAM)


$(MYPROGRAM): $(SOURCE)
	$(CC)  $(SOURCE) -o$(MYPROGRAM) 
	#$(CC) -I$(MYINCLUDES) $(SOURCE) -o$(MYPROGRAM) -l$(MYLIBRARIES)

clean:
	rm -fltk $(MYPROGRAM)






